---
all:
  children: 
    control:
      hosts:
        Control-Node:
          ansible_user: ubuntu
          ansible_become: true
          ansible_connection: local
          
    RackServers:
      hosts:
          lightsail-srv1: # 54.227.21.17:
          nagios_tmp_client: # 54.164.113.65:   
          # CYPQ-16: # - 10.10.10.49/50 
          # CYPQ-17: # - 10.10.10.51/52 
          # CYPQ-18: # - 10.10.10.53/54 
          # CYPQ-19: # - 10.10.10.55/56 
          # CYPQ-20: # - 10.10.10.57/58 

          # WFP-23: # - 10.10.10.75/76 
          # WFP-09: # - 10.10.10.69/70
          # WFP-22: # - 10.10.10.79/80 
          # WFP-24: # - 10.10.10.77/78  

      vars:
          ansible_user: ubuntu
          ansible_become: true
          ansible_become_user: root
          host_key_checking: False

    RackServers_RedHat:       
      hosts:
          NagiosTmpClient-2: # 23.20.182.2:
      vars:
          ansible_user: centos
          ansible_become: true
          ansible_become_user: root
          host_key_checking: False

